//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShotBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenShotBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort?.
        /// </summary>
        internal static string caption_AbortRunningProcess {
            get {
                return ResourceManager.GetString("caption_AbortRunningProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string caption_info {
            get {
                return ResourceManager.GetString("caption_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite?.
        /// </summary>
        internal static string caption_Overwrite {
            get {
                return ResourceManager.GetString("caption_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormClosing done..
        /// </summary>
        internal static string debug_ApplicationFormClosingDone {
            get {
                return ResourceManager.GetString("debug_ApplicationFormClosingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormClosing started..
        /// </summary>
        internal static string debug_ApplicationFormClosingStarted {
            get {
                return ResourceManager.GetString("debug_ApplicationFormClosingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created [{0}]..
        /// </summary>
        internal static string debug_XmlCreated {
            get {
                return ResourceManager.GetString("debug_XmlCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating [{0}]..
        /// </summary>
        internal static string debug_XmlCreating {
            get {
                return ResourceManager.GetString("debug_XmlCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded [{0}]..
        /// </summary>
        internal static string debug_XmlLoaded {
            get {
                return ResourceManager.GetString("debug_XmlLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading [{0}]..
        /// </summary>
        internal static string debug_XmlLoading {
            get {
                return ResourceManager.GetString("debug_XmlLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved [{0}]..
        /// </summary>
        internal static string debug_XmlSaved {
            get {
                return ResourceManager.GetString("debug_XmlSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving [{0}]..
        /// </summary>
        internal static string debug_XmlSaving {
            get {
                return ResourceManager.GetString("debug_XmlSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create process....
        /// </summary>
        internal static string error_FailedToCreateProcess {
            get {
                return ResourceManager.GetString("error_FailedToCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists: [{0}].
        /// </summary>
        internal static string error_FileAlreadyExists {
            get {
                return ResourceManager.GetString("error_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video converter returned an error..
        /// </summary>
        internal static string error_VideoConverterReturnsError {
            get {
                return ResourceManager.GetString("error_VideoConverterReturnsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create [{0}]..
        /// </summary>
        internal static string error_XmlCreatingFailed {
            get {
                return ResourceManager.GetString("error_XmlCreatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load [{0}]..
        /// </summary>
        internal static string error_XmlLoadingFailed {
            get {
                return ResourceManager.GetString("error_XmlLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save [{0}]..
        /// </summary>
        internal static string error_XmlSavingFailed {
            get {
                return ResourceManager.GetString("error_XmlSavingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconGreen {
            get {
                object obj = ResourceManager.GetObject("IconGreen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconRed1 {
            get {
                object obj = ResourceManager.GetObject("IconRed1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconRed2 {
            get {
                object obj = ResourceManager.GetObject("IconRed2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconRed3 {
            get {
                object obj = ResourceManager.GetObject("IconRed3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon IconRed4 {
            get {
                object obj = ResourceManager.GetObject("IconRed4", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of Screenshot Bot is already running..
        /// </summary>
        internal static string info_ApplicationAlreadyRunning {
            get {
                return ResourceManager.GetString("info_ApplicationAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Bot started. Version {0}..
        /// </summary>
        internal static string info_ApplicationStarted {
            get {
                return ResourceManager.GetString("info_ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Bot stopped..
        /// </summary>
        internal static string info_ApplicationStopped {
            get {
                return ResourceManager.GetString("info_ApplicationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter: {0}.
        /// </summary>
        internal static string info_ConverterOutput {
            get {
                return ResourceManager.GetString("info_ConverterOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string info_Counter {
            get {
                return ResourceManager.GetString("info_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string info_DateDay {
            get {
                return ResourceManager.GetString("info_DateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string info_DateHour {
            get {
                return ResourceManager.GetString("info_DateHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string info_DateMinute {
            get {
                return ResourceManager.GetString("info_DateMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string info_DateMonth {
            get {
                return ResourceManager.GetString("info_DateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string info_DateSecond {
            get {
                return ResourceManager.GetString("info_DateSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string info_DateYear {
            get {
                return ResourceManager.GetString("info_DateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory: [{0}].
        /// </summary>
        internal static string info_DumpDirectory {
            get {
                return ResourceManager.GetString("info_DumpDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval: [{0}] {1}.
        /// </summary>
        internal static string info_DumpInterval {
            get {
                return ResourceManager.GetString("info_DumpInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen: Index={0}, Primary={1}, Device={2}, Bounds={3}, BitDepth={4}.
        /// </summary>
        internal static string info_DumpScreen {
            get {
                return ResourceManager.GetString("info_DumpScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file [{0}] already exists.
        ///
        ///Overwrite?.
        /// </summary>
        internal static string info_FileExistsOverwrite {
            get {
                return ResourceManager.GetString("info_FileExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subdirs.
        /// </summary>
        internal static string info_IncludeSubDirs {
            get {
                return ResourceManager.GetString("info_IncludeSubDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No screens detected.
        /// </summary>
        internal static string info_NoScreensDetected {
            get {
                return ResourceManager.GetString("info_NoScreensDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subdirs.
        /// </summary>
        internal static string info_NoSubDirs {
            get {
                return ResourceManager.GetString("info_NoSubDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only subdirs.
        /// </summary>
        internal static string info_OnlySubDirs {
            get {
                return ResourceManager.GetString("info_OnlySubDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to abort the running process?.
        /// </summary>
        internal static string info_ReallyAbortRunningProcess {
            get {
                return ResourceManager.GetString("info_ReallyAbortRunningProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to height (px).
        /// </summary>
        internal static string info_ScaleHeight {
            get {
                return ResourceManager.GetString("info_ScaleHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string info_ScaleOriginal {
            get {
                return ResourceManager.GetString("info_ScaleOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen {0}.
        /// </summary>
        internal static string info_Screen {
            get {
                return ResourceManager.GetString("info_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen {0} (Primary).
        /// </summary>
        internal static string info_ScreenPrimary {
            get {
                return ResourceManager.GetString("info_ScreenPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting screenshot capture..
        /// </summary>
        internal static string info_ScreenshotCaptureStarting {
            get {
                return ResourceManager.GetString("info_ScreenshotCaptureStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped screenshot capture..
        /// </summary>
        internal static string info_ScreenshotCaptureStopped {
            get {
                return ResourceManager.GetString("info_ScreenshotCaptureStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping screenshot capture. Reason: {0}.
        /// </summary>
        internal static string info_ScreenshotCaptureStopping {
            get {
                return ResourceManager.GetString("info_ScreenshotCaptureStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string info_Start {
            get {
                return ResourceManager.GetString("info_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to take screenshots..
        /// </summary>
        internal static string info_StartScreenShots {
            get {
                return ResourceManager.GetString("info_StartScreenShots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string info_StatusError {
            get {
                return ResourceManager.GetString("info_StatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        internal static string info_StatusReady {
            get {
                return ResourceManager.GetString("info_StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running....
        /// </summary>
        internal static string info_StatusRunning {
            get {
                return ResourceManager.GetString("info_StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string info_StatusStarting {
            get {
                return ResourceManager.GetString("info_StatusStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string info_StatusStopping {
            get {
                return ResourceManager.GetString("info_StatusStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string info_Stop {
            get {
                return ResourceManager.GetString("info_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted by user..
        /// </summary>
        internal static string info_StopReasonAborted {
            get {
                return ResourceManager.GetString("info_StopReasonAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string info_VideoConverterDone {
            get {
                return ResourceManager.GetString("info_VideoConverterDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting video converter..
        /// </summary>
        internal static string info_VideoConverterStarting {
            get {
                return ResourceManager.GetString("info_VideoConverterStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped video converter..
        /// </summary>
        internal static string info_VideoConverterStopped {
            get {
                return ResourceManager.GetString("info_VideoConverterStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping video converter. Reason: {0}.
        /// </summary>
        internal static string info_VideoConverterStopping {
            get {
                return ResourceManager.GetString("info_VideoConverterStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string IntervalUnit_Days {
            get {
                return ResourceManager.GetString("IntervalUnit_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string IntervalUnit_Hours {
            get {
                return ResourceManager.GetString("IntervalUnit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string IntervalUnit_Minutes {
            get {
                return ResourceManager.GetString("IntervalUnit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        internal static string IntervalUnit_MSecs {
            get {
                return ResourceManager.GetString("IntervalUnit_MSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string IntervalUnit_Secs {
            get {
                return ResourceManager.GetString("IntervalUnit_Secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid framerate....
        /// </summary>
        internal static string tooltip_InvalidFramerate {
            get {
                return ResourceManager.GetString("tooltip_InvalidFramerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scale....
        /// </summary>
        internal static string tooltip_InvalidScale {
            get {
                return ResourceManager.GetString("tooltip_InvalidScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screen....
        /// </summary>
        internal static string tooltip_InvalidScreen {
            get {
                return ResourceManager.GetString("tooltip_InvalidScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screenshot filenames....
        /// </summary>
        internal static string tooltip_InvalidScreenShotFilename {
            get {
                return ResourceManager.GetString("tooltip_InvalidScreenShotFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screenshot interval....
        /// </summary>
        internal static string tooltip_InvalidScreenShotInterval {
            get {
                return ResourceManager.GetString("tooltip_InvalidScreenShotInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid screenshot subdirectory....
        /// </summary>
        internal static string tooltip_InvalidScreenShotSubDir {
            get {
                return ResourceManager.GetString("tooltip_InvalidScreenShotSubDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input directory....
        /// </summary>
        internal static string tooltip_InvalidVideoInputDir {
            get {
                return ResourceManager.GetString("tooltip_InvalidVideoInputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output filename....
        /// </summary>
        internal static string tooltip_InvalidVideoOutputFilename {
            get {
                return ResourceManager.GetString("tooltip_InvalidVideoOutputFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid output path....
        /// </summary>
        internal static string tooltip_InvalidVideoOutputPath {
            get {
                return ResourceManager.GetString("tooltip_InvalidVideoOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot directory not found....
        /// </summary>
        internal static string tooltip_ScreenShotDirectoryNotFound {
            get {
                return ResourceManager.GetString("tooltip_ScreenShotDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffmpeg path not found....
        /// </summary>
        internal static string tooltip_VideoConverterPathNotFound {
            get {
                return ResourceManager.GetString("tooltip_VideoConverterPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory does not exist....
        /// </summary>
        internal static string tooltip_VideoOutpuDirDoesNotExist {
            get {
                return ResourceManager.GetString("tooltip_VideoOutpuDirDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread captures screenshot..
        /// </summary>
        internal static string trace_ThreadGettingScreenShot {
            get {
                return ResourceManager.GetString("trace_ThreadGettingScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread has no screen selected..
        /// </summary>
        internal static string trace_ThreadNoScreen {
            get {
                return ResourceManager.GetString("trace_ThreadNoScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread will sleep..
        /// </summary>
        internal static string trace_ThreadSleep {
            get {
                return ResourceManager.GetString("trace_ThreadSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread is stopping..
        /// </summary>
        internal static string trace_ThreadStopping {
            get {
                return ResourceManager.GetString("trace_ThreadStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread updates preview..
        /// </summary>
        internal static string trace_ThreadUpdatingPreview {
            get {
                return ResourceManager.GetString("trace_ThreadUpdatingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread woke up..
        /// </summary>
        internal static string trace_ThreadWokeUp {
            get {
                return ResourceManager.GetString("trace_ThreadWokeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input files found....
        /// </summary>
        internal static string warn_NoInputFilesFound {
            get {
                return ResourceManager.GetString("warn_NoInputFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen cannot be captured at the moment. Reason: {0}.
        /// </summary>
        internal static string warn_ScreenCannotBeCapturedNow {
            get {
                return ResourceManager.GetString("warn_ScreenCannotBeCapturedNow", resourceCulture);
            }
        }
    }
}
