//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShotBot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptionScreenShotDir {
            get {
                return ((string)(this["OptionScreenShotDir"]));
            }
            set {
                this["OptionScreenShotDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int OptionScreenIndex {
            get {
                return ((int)(this["OptionScreenIndex"]));
            }
            set {
                this["OptionScreenIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public float OptionScreenShotInterval {
            get {
                return ((float)(this["OptionScreenShotInterval"]));
            }
            set {
                this["OptionScreenShotInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int OptionScreenShotIntervalUnits {
            get {
                return ((int)(this["OptionScreenShotIntervalUnits"]));
            }
            set {
                this["OptionScreenShotIntervalUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OptionResetStatusAfterStart {
            get {
                return ((bool)(this["OptionResetStatusAfterStart"]));
            }
            set {
                this["OptionResetStatusAfterStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{yy}-{MM}-{dd}")]
        public string OptionScreenShotSubDir {
            get {
                return ((string)(this["OptionScreenShotSubDir"]));
            }
            set {
                this["OptionScreenShotSubDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Screenshot_{0000000}.png")]
        public string OptionScreenShotFilename {
            get {
                return ((string)(this["OptionScreenShotFilename"]));
            }
            set {
                this["OptionScreenShotFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptionScreenShotExtension {
            get {
                return ((int)(this["OptionScreenShotExtension"]));
            }
            set {
                this["OptionScreenShotExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int OptionLogLevel {
            get {
                return ((int)(this["OptionLogLevel"]));
            }
            set {
                this["OptionLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptionVideoConverterPath {
            get {
                return ((string)(this["OptionVideoConverterPath"]));
            }
            set {
                this["OptionVideoConverterPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.png")]
        public string OptionVideoFilePattern {
            get {
                return ((string)(this["OptionVideoFilePattern"]));
            }
            set {
                this["OptionVideoFilePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float OptionVideoImagesPerSecond {
            get {
                return ((float)(this["OptionVideoImagesPerSecond"]));
            }
            set {
                this["OptionVideoImagesPerSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptionVideoScaleType {
            get {
                return ((int)(this["OptionVideoScaleType"]));
            }
            set {
                this["OptionVideoScaleType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int OptionVideoScale {
            get {
                return ((int)(this["OptionVideoScale"]));
            }
            set {
                this["OptionVideoScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..")]
        public string OptionVideoOutputDir {
            get {
                return ((string)(this["OptionVideoOutputDir"]));
            }
            set {
                this["OptionVideoOutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptionVideoConverterCustomCommand {
            get {
                return ((string)(this["OptionVideoConverterCustomCommand"]));
            }
            set {
                this["OptionVideoConverterCustomCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OptionUseVideoConverterCustomCommand {
            get {
                return ((bool)(this["OptionUseVideoConverterCustomCommand"]));
            }
            set {
                this["OptionUseVideoConverterCustomCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int OptionVideoSubDirsType {
            get {
                return ((int)(this["OptionVideoSubDirsType"]));
            }
            set {
                this["OptionVideoSubDirsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Timelapse-{yy}-{MM}-{dd}.mp4")]
        public string OptionVideoOutputFilename {
            get {
                return ((string)(this["OptionVideoOutputFilename"]));
            }
            set {
                this["OptionVideoOutputFilename"] = value;
            }
        }
    }
}
